[package]
name = "cshell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.35", features = ["derive"] }
thiserror = "2.0.12"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
clang = {version="2.0.0", features=["runtime", "clang_10_0"]}
