[project]
name = "cshell"
version = "0.0.0"
edition = "0.1.0"

[[todo]]
name = "add more shell commands"
priority = 0.8
difficulty = 0.5

[[todo]]
name = "create shared object libraries"
priority = 0.8
difficulty = 0.5

[[todo]]
name = "improve allocators"
priority = 0.8
difficulty = 0.5

[[done]]
name = "basic mem debugger"
priority = 0.2
difficulty = 0.1

[[done]]
name = "execute binaries from /bin"
priority = 0.4
difficulty = 0.1

[[done]]
name = "execute chell programs"
priority = 0.4
difficulty = 0.1
