[project]
name = "cshell"
version = "0.0"
edition = "1.0"

[[todo]]
name = "add more shell commands"
priority = 8
difficulty = 5

[[todo]]
name = "create shared object libraries"
priority = 8
difficulty = 5

[[todo]]
name = "improve allocators"
priority = 8
difficulty = 5

[[done]]
name = "basic mem debugger"
priority = 2
difficulty = 1

[[done]]
name = "execute binaries from /bin"
priority = 4
difficulty = 1

[[done]]
name = "execute chell programs"
priority = 4
difficulty = 1
