#ifndef __BIND_GEN__
#define __BIND_GEN__

/* Generated with cbindgen:0.28.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

typedef struct Args Args;

void free_args(struct Args*);

const char *get_script(struct Args *const *args);

bool is_debug(struct Args *const *args);

struct Args *parse_args(int argc, const char *const *argv);

#endif  /* __BIND_GEN__ */
