#ifndef __VECTOR_PRIMITIVES__
#define __VECTOR_PRIMITIVES__

#include "vector.h"
#include "defs.h"

DECLARE_VECTOR(u8)
DECLARE_VECTOR(u16)
DECLARE_VECTOR(u32)
DECLARE_VECTOR(u64)
DECLARE_VECTOR(i8)
DECLARE_VECTOR(i16)
DECLARE_VECTOR(i32)
DECLARE_VECTOR(i64)
DECLARE_VECTOR(f32)
DECLARE_VECTOR(f64)
DECLARE_VECTOR(str)

#endif
