#include "generic_objects.h"
#include "object.h"

DEFINE_TYPE(char)
DEFINE_TYPE(u8)
DEFINE_TYPE(u16)
DEFINE_TYPE(u32)
DEFINE_TYPE(u64)
DEFINE_TYPE(i8)
DEFINE_TYPE(i16)
DEFINE_TYPE(i32)
DEFINE_TYPE(i64)

DEFINE_TYPE(f32)
DEFINE_TYPE(f64)

DEFINE_TYPE(str)
DEFINE_TYPE(string)


DEFINE_DEFAULT(char) '\0';

DEFINE_DEFAULT(u8)  0;
DEFINE_DEFAULT(u16) 0;
DEFINE_DEFAULT(u32) 0;
DEFINE_DEFAULT(u64) 0;

DEFINE_DEFAULT(i8)  0;
DEFINE_DEFAULT(i16) 0;
DEFINE_DEFAULT(i32) 0;
DEFINE_DEFAULT(i64) 0;

DEFINE_DEFAULT(f32) 0;
DEFINE_DEFAULT(f64) 0;

DEFINE_DEFAULT(str) 0;
DEFINE_DEFAULT(string) {NULL, 0};

void __init_generic_objects(){
	INIT_TYPE(char)
	INIT_TYPE(u8)
	INIT_TYPE(u16)
	INIT_TYPE(u32)
	INIT_TYPE(u64)
	INIT_TYPE(i8)
	INIT_TYPE(i16)
	INIT_TYPE(i32)
	INIT_TYPE(i64)
	INIT_TYPE(f32)
	INIT_TYPE(f64)
	INIT_TYPE(str)
	INIT_TYPE(string)
}
